/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#7ffc97",
        "surface-container-lowest": "#000f21",
        "on-tertiary-container": "#3e2400",
        "error": "#ffb4ab",
        "on-primary-container": "#003111",
        "error-container": "#93000a",
        "on-tertiary": "#472a00",
        "on-error": "#690005",
        "outline": "#879485",
        "on-surface": "#d3e4fe",
        "surface-variant": "#26364a",
        "outline-variant": "#3e4a3d",
        "tertiary": "#ffb95f",
        "surface-container-low": "#0b1c30",
        "surface-container": "#102034",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-fixed": "#0d1c2c",
        "tertiary-container": "#ca8100",
        "surface-dim": "#031427",
        "secondary": "#b9c8dd",
        "secondary-fixed-dim": "#b9c8dd",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary": "#233142",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#213145",
        "on-primary-fixed-variant": "#005320",
        "primary-fixed-dim": "#62df7d",
        "surface": "#031427",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#002109",
        "on-surface-variant": "#bdcaba",
        "surface-container-high": "#1b2b3f",
        "surface-container-highest": "#26364a",
        "on-background": "#d3e4fe",
        "secondary-container": "#3a485a",
        "inverse-surface": "#d3e4fe",
        "on-secondary-container": "#a7b6cb",
        "inverse-primary": "#006e2d",
        "surface-bright": "#2a3a4f",
        "on-secondary-fixed-variant": "#3a485a",
        "primary": "#62df7d",
        "surface-tint": "#62df7d",
        "background": "#031427",
        "on-primary": "#003914",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#1ca64d",
        "secondary-fixed": "#d5e4fa"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "margin-mobile": "16px",
        "lg": "24px",
        "sm": "8px",
        "margin-desktop": "64px",
        "xs": "4px",
        "gutter": "16px",
        "base": "4px",
        "xl": "32px"
      },
      fontFamily: {
        "headline-md": ["Poppins", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Poppins", "sans-serif"],
        "headline-md-mobile": ["Poppins", "sans-serif"],
        "headline-sm": ["Poppins", "sans-serif"],
        "headline-xl": ["Poppins", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-md-mobile": ["22px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
